[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 8084
  autoLaunch = true

# Headers for proper MIME types
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/icons/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/debug/categories"
  to = "/.netlify/functions/debug-categories"
  status = 200

[[redirects]]
  from = "/api/test/frontend-config"
  to = "/.netlify/functions/test-frontend-config"
  status = 200

[[redirects]]
  from = "/api/knowledge-base/categories"
  to = "/.netlify/functions/knowledge-base-categories"
  status = 200

[[redirects]]
  from = "/api/knowledge-base/items"
  to = "/.netlify/functions/knowledge-base-items"
  status = 200

[[redirects]]
  from = "/api/knowledge-base/upload"
  to = "/.netlify/functions/knowledge-base-upload"
  status = 200

[[redirects]]
  from = "/api/knowledge-base/compression-stats"
  to = "/.netlify/functions/compression-stats"
  status = 200

[[redirects]]
  from = "/api/chat/message"
  to = "/.netlify/functions/chat-message"
  status = 200

# New redirects for missing endpoints
[[redirects]]
  from = "/api/pdf"
  to = "/.netlify/functions/pdf"
  status = 200

[[redirects]]
  from = "/api/pdf/*"
  to = "/.netlify/functions/pdf"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/api/notes/*"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/api/folders"
  to = "/.netlify/functions/folders"
  status = 200

[[redirects]]
  from = "/api/folders/*"
  to = "/.netlify/functions/folders"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 